D8CORE-1468-IE-fix: fix flex rule for IE
SU-SWS/react_paragraphs pull request #22
Opened 2020-03-05 01:21 UTC by cjwest

# READY FOR REVIEW

# Summary
Not all flex rules work for IE. This change appears to work on IE, Edge, Chrome, and Firefox

# Review By (Date)
- Soonish. 

# Urgency
- It makes full with pages readable on IE.

# Steps to Test
Because my local environment is AWOL, I'm not able to verify this works in code.

1. Pull this branch
2. Rebuild as necessary
3. Verify correct homepage layout on IE, Edge, Chrome, and Firefox
4. Verify any full with page displays as expected.

# Affected Projects or Products
- D8Core

# Associated Issues and/or People
- JIRA ticket: https://stanfordits.atlassian.net/browse/D8CORE-1468

- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2020-03-05 03:08 UTC, pookmish requested changes

2020-03-05 03:08 UTC, pookmish commented on css/react_paragraphs.field_formatter.css
> +          flex: 12 1 auto; }
lets apply this to all of the other selectors.

2020-03-07 01:05 UTC, sherakama commented
@cjwest if you want to win big time extra kudo points you could also help my implementing a webpack compiler with all the bells and whistles.

2020-03-07 01:21 UTC, pookmish commented
I'm not sure if it's possible to repurpose the web pack compiler in the `js` directory.  Worth some trials

2020-03-09 18:10 UTC, pookmish commented
this might be solved by https://github.com/SU-SWS/react_paragraphs/pull/24
check out: https://github.com/SU-SWS/react_paragraphs/pull/24/files#diff-cf45b848d4c21047f468c8fe61625f29

I've also moved around the webpack compiler and got it to compile the scss

2020-03-13 05:05 UTC, sherakama commented
@cjwest ping.

2020-03-13 20:03 UTC, pookmish commented
I think we'll close this since the styles will be very different once the other PR is merged

2020-03-13 20:03 UTC, closed without merging